### Ручной вызов обновления рейсов =
POST https://localhost:7045/api/admin/update-flights
Accept: application/json

### Получить все рейсы
GET https://localhost:7045/api/flight
Accept: application/json


### Добавить рейс вручную
POST https://localhost:7045/api/flight
Content-Type: application/json

{
  "flightNumber": "SU1235",
  "departureTime": "2025-05-01T10:00:00Z",
  "status": "on_time"
}


### Обновить рейс (id = 1)
PUT https://localhost:7045/api/flight/1
Content-Type: application/json

{
  "flightNumber": "SU1235",
  "departureTime": "2025-05-01T10:00:00Z",
  "status": "delayed"
}

### Очистить базу данных рейсов
DELETE https://localhost:7045/api/flight/clear
Accept: application/json

### Получить рейс по номеру и дате
GET https://localhost:7045/api/flight/search?flightNumber=U6299
Accept: application/json
